community/objects/Rate__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipLabel>Job Rate Cards</relationshipLabel>
        <relationshipName>Rate_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <displayFormat>RATE-{MMDDYY}-{000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

community/objects/Rate_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Over_12_Bill_Rate__c</fullName>
        <label>Over 12 Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Over_12_Pay_Rate__c</fullName>
        <label>Over 12 Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Over_40_Bill_Rate__c</fullName>
        <label>Over 40 Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Over_40_Pay_Rate__c</fullName>
        <label>Over 40 Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Over_8_Bill_Rate__c</fullName>
        <label>Over 8 Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Over_8_Pay_Rate__c</fullName>
        <label>Over 8 Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <label>Rate Card</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Rate Card Details</relationshipLabel>
        <relationshipName>Rate_Card_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Regular_Bill_Rate__c</fullName>
        <label>Regular Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Regular_Pay_Rate__c</fullName>
        <label>Regular Pay Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Time_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Type</label>
        <referenceTo>Time_Type__c</referenceTo>
        <relationshipLabel>Rate Card Details</relationshipLabel>
        <relationshipName>Rate_Card_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Card Detail</label>
    <nameField>
        <displayFormat>RCD-{MMDDYY}-{000}</displayFormat>
        <label>Rate Card Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

community/objects/Time_Type__c.object
<CustomObject>
    <fields>
        <fullName>Functions__c</fullName>
        <label>Functions</label>
        <picklist>
            <picklistValues>
                <fullName>Designer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LPN: Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LPN: Non-Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA: Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA: Non-Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MPAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RN: Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RN: Non-Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payor: Clinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payor: Non-Clinical</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Time Type</label>
    <nameField>
        <label>Time Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

community/classes/MassRateCardDetailEditPageControllerTest.cls
@isTest
public class MassRateCardDetailEditPageControllerTest{
    static testMethod void saveTest(){
    
        //When User Clicks on Save Button
        
        Time_Type__c testTimeType1 = new Time_Type__c(Functions__c = 'Test1;Test2;Test3');
        insert testTimeType1;
        
        Time_Type__c testTimeType2 = new Time_Type__c(Functions__c = 'Test2;Test3');
        insert testTimeType2;
        
        Time_Type__c testTimeType3 = new Time_Type__c(Functions__c = 'Test3');
        insert testTimeType3;
        
        Account newAcc = new Account(Name = 'Test Acct');
        insert newAcc;
        
        TR1__Job__c testJob = new TR1__Job__c(Name = 'Test Job', TR1__Account__c = newAcc.Id, TR1__Division__c = 'Test2');
        insert testJob;
        
        Id contractRateCardType = Schema.SObjectType.Rate__c.getRecordTypeInfosByName().get('Contracted Rate Card').getRecordTypeId();
        Rate__c contract_rate = new Rate__c(RecordTypeId = contractRateCardType, Job__c = testJob.Id);
        insert contract_rate;
        
        Test.setCurrentPage(page.MassRateCardDetailEditPage);
        ApexPages.StandardController sc = new ApexPages.StandardController(contract_rate);
        MassRateCardDetailEditPageController controller = new MassRateCardDetailEditPageController(sc);
        controller.save();
    }
    
    static testMethod void cancelTest(){

        //When User Clicks on Cancel Button
    
        Time_Type__c testTimeType1 = new Time_Type__c(Functions__c = 'Test1;Test2;Test3');
        insert testTimeType1;
        
        Time_Type__c testTimeType2 = new Time_Type__c(Functions__c = 'Test2;Test3');
        insert testTimeType2;
        
        Time_Type__c testTimeType3 = new Time_Type__c(Functions__c = 'Test3');
        insert testTimeType3;
        
        Account newAcc = new Account(Name = 'Test Acct');
        insert newAcc;
        
        TR1__Job__c testJob = new TR1__Job__c(Name = 'Test Job', TR1__Account__c = newAcc.Id, TR1__Division__c = 'Test2');
        insert testJob;
        
        Id contractRateCardType = Schema.SObjectType.Rate__c.getRecordTypeInfosByName().get('Contracted Rate Card').getRecordTypeId();
        Rate__c contract_rate = new Rate__c(RecordTypeId = contractRateCardType, Job__c = testJob.Id);
        insert contract_rate;
        
        List< Rate_Card_Detail__c > testRateCardDetailList = [Select Id from Rate_Card_Detail__c where Rate_Card__c =: contract_rate.id];
        
        for(Rate_Card_Detail__c rcd : testRateCardDetailList){
            rcd.Regular_Pay_Rate__c = 10.00;
            rcd.Over_8_Pay_Rate__c = 20.00;
            rcd.Over_12_Pay_Rate__c = 30.00;
            rcd.Over_40_Pay_Rate__c = 40.00;
            rcd.Regular_Bill_Rate__c = 10.00;
            rcd.Over_8_Bill_Rate__c = 20.00;
            rcd.Over_12_Bill_Rate__c = 30.00;
            rcd.Over_40_Bill_Rate__c = 40.00;
        }
        
        Map< Id , Rate_Card_Detail__c > testRateCardDetailMap = new Map< Id , Rate_Card_Detail__c >([Select Id, Regular_Pay_Rate__c, Over_8_Pay_Rate__c, Over_12_Pay_Rate__c, Over_40_Pay_Rate__c, Regular_Bill_Rate__c, Over_8_Bill_Rate__c, Over_12_Bill_Rate__c, Over_40_Bill_Rate__c from Rate_Card_Detail__c where Rate_Card__c =: contract_rate.id]);
        
        Test.setCurrentPage(page.MassRateCardDetailEditPage);
        ApexPages.StandardController sc = new ApexPages.StandardController(contract_rate);
        MassRateCardDetailEditPageController controller = new MassRateCardDetailEditPageController(sc);
        controller.cancel();
        
        List< Rate_Card_Detail__c > testRateCardDetailListUpdated = [Select Id, Regular_Pay_Rate__c, Over_8_Pay_Rate__c, Over_12_Pay_Rate__c, Over_40_Pay_Rate__c, Regular_Bill_Rate__c, Over_8_Bill_Rate__c, Over_12_Bill_Rate__c, Over_40_Bill_Rate__c from Rate_Card_Detail__c where Rate_Card__c =: contract_rate.id];
        
        for(Rate_Card_Detail__c rcd : testRateCardDetailListUpdated){
            System.assertEquals(testRateCardDetailMap.get(rcd.id).Regular_Pay_Rate__c,rcd.Regular_Pay_Rate__c,'Rate remains unchanged on Rate Card Detail when user clicks on Cancel Button.');
            System.assertEquals(testRateCardDetailMap.get(rcd.id).Over_8_Pay_Rate__c,rcd.Over_8_Pay_Rate__c,'Rate remains unchanged on Rate Card Detail when user clicks on Cancel Button.');
            System.assertEquals(testRateCardDetailMap.get(rcd.id).Over_12_Pay_Rate__c,rcd.Over_12_Pay_Rate__c,'Rate remains unchanged on Rate Card Detail when user clicks on Cancel Button.');
            System.assertEquals(testRateCardDetailMap.get(rcd.id).Over_40_Pay_Rate__c,rcd.Over_40_Pay_Rate__c,'Rate remains unchanged on Rate Card Detail when user clicks on Cancel Button.');
            System.assertEquals(testRateCardDetailMap.get(rcd.id).Regular_Bill_Rate__c,rcd.Regular_Bill_Rate__c,'Rate remains unchanged on Rate Card Detail when user clicks on Cancel Button.');
            System.assertEquals(testRateCardDetailMap.get(rcd.id).Over_8_Bill_Rate__c,rcd.Over_8_Bill_Rate__c,'Rate remains unchanged on Rate Card Detail when user clicks on Cancel Button.');
            System.assertEquals(testRateCardDetailMap.get(rcd.id).Over_12_Bill_Rate__c,rcd.Over_12_Bill_Rate__c,'Rate remains unchanged on Rate Card Detail when user clicks on Cancel Button.');
            System.assertEquals(testRateCardDetailMap.get(rcd.id).Over_40_Bill_Rate__c,rcd.Over_40_Bill_Rate__c,'Rate remains unchanged on Rate Card Detail when user clicks on Cancel Button.');
        }

        
    }
    
    static testMethod void SaveTestNegativeTest(){

        //When User Clicks on save Button but rate record is not present.
    
        Time_Type__c testTimeType1 = new Time_Type__c(Functions__c = 'Test1;Test2;Test3');
        insert testTimeType1;
        
        Time_Type__c testTimeType2 = new Time_Type__c(Functions__c = 'Test2;Test3');
        insert testTimeType2;
        
        Time_Type__c testTimeType3 = new Time_Type__c(Functions__c = 'Test3');
        insert testTimeType3;
        
        Account newAcc = new Account(Name = 'Test Acct');
        insert newAcc;
        
        TR1__Job__c testJob = new TR1__Job__c(Name = 'Test Job', TR1__Account__c = newAcc.Id, TR1__Division__c = 'Test2');
        insert testJob;
        
        Id contractRateCardType = Schema.SObjectType.Rate__c.getRecordTypeInfosByName().get('Contracted Rate Card').getRecordTypeId();
        Rate__c contract_rate = new Rate__c(RecordTypeId = contractRateCardType, Job__c = testJob.Id);
        insert contract_rate;
        
        Test.setCurrentPage(page.MassRateCardDetailEditPage);
        ApexPages.StandardController sc = new ApexPages.StandardController(contract_rate);
        
        delete contract_rate;
        
        MassRateCardDetailEditPageController controller = new MassRateCardDetailEditPageController(sc);
        controller.save();
    }
}